spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update


#  liquibase:
#    enabled: true
#    change-log: classpath:/liquibase/changelog-master.yml
#    database-change-log-table: DATABASECHANGELOG
#    database-change-log-lock-table: DATABASECHANGELOGLOCK

